Some MeiliSearch v0.21.0 related changes
meilisearch/meilisearch-rust pull request #150
Opened 2021-07-17 12:30 UTC by juzi5201314

https://github.com/meilisearch/integration-guides/issues/117
change: 
- Ranaming of buildDate into commitDate
- New update status value
- attributesForFaceting is renamed into filterableAttributes
- Rename fieldsDistribution into fieldDistribution
- filters is renamed into filter
- facetFilters is removed

2021-07-19 09:52 UTC, bidoubiwa requested changes
Hello, thanks so much for this pr 🔥 Small changes that were not included in this PR: 

- `settings.rs` lines 298, 495, 698 `[attributes for faceting]` in the comments should be changed with `filterable attributes`
- `settings.rs` lines 310, 513, 715 should have their API route updated `&format!("{}/indexes/{}/settings/attributes-for-faceting", self.host, self.uid),` to `/filterable-attributes`
- `.code-samples.meilisearch.yaml` 511, 535 `with_facet_filters` should be removed

2021-07-19 09:52 UTC, bidoubiwa commented on src/search.rs
> +    pub filter: Option<&'a str>,
The type of fillter is the same as `facet_filters` but can also accept a `str` as value. So it's a mix of both `filter` and `facet_filters`. 
The following syntaxes are possible: 

nested array:
```json
["something > 1", "genre=comedy", ["genre=horror", "title=batman"]]
```
only string: 
```json
"something > 1 AND genre=comedy AND (genre=horror OR title=batman)"
```

of course both are also mixable
```json
["something > 1 AND genre=comedy", "genre=horror OR title=batman"]
```

2021-07-19 09:52 UTC, bidoubiwa commented on src/search.rs
> +        self.filter = Some(filter);
Should be updated based on type update.

2021-07-19 09:52 UTC, bidoubiwa commented on src/search.rs
> -            .unwrap();
Could you do these tests on `filter` ?

2021-07-19 09:52 UTC, bidoubiwa commented on src/search.rs
> +        //query.with_facet_filters(&[&["kind:text"]]);
should be uncommented

2021-07-19 09:52 UTC, bidoubiwa commented on src/progress.rs
> +    },
Thanks a lot for raising this change, was this documented somewhere?

I have made an issue to know if this is the expected behavior or not: see meilisearch/MeiliSearch/issues/1517

2021-07-20 19:11 UTC, bidoubiwa commented on src/search.rs
> +    pub filter: Option<&'a str>,
After some thought we may also just only accept the string format. What do you think?

2021-08-04 08:41 UTC, curquiza commented
Since we don't have answer of the contributor, I merge and I will apply the changes myself :)

2021-08-04 08:44 UTC, merged