Added an example using actix-web, async_graphql and diesel
meilisearch/meilisearch-rust pull request #538
Opened 2023-12-20 13:10 UTC by korir248

# Pull Request

## Related issue
Fixes #247

## What does this PR do?
- Adds an example which depivts using `actix-web` and `async_graphql` to query records in a `postgres` database 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2024-01-03 21:04 UTC, korir248 commented
@curquiza can you take a look

2024-01-31 09:23 UTC, curquiza commented on examples/web_app_graphql/.gitignore
> +.env
```suggestion
.env
```

2024-02-27 17:19 UTC, irevoire commented
Hey, thanks, codewise the example is impressive. That’s awesome; I’m not familiar myself with `diesel` or graph ql, so having such an example in the repository is awesome!

But when I tried to `cargo run --release` the example, I got the following error:
```
= note: ld: library not found for -lpq
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any idea why that would be the format?

2024-02-27 18:06 UTC, irevoire requested changes
Oh, and also, could you rename your `Readme.md` into `README.md`.

2024-02-27 18:15 UTC, korir248 commented
> Hey, thanks, codewise the example is impressive. That’s awesome; I’m not familiar myself with `diesel` or graph ql, so having such an example in the repository is awesome!
> 
> But when I tried to `cargo run --release` the example, I got the following error:
> 
> ```
> = note: ld: library not found for -lpq
>           clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Any idea why that would be the format?

Yes. `libpq-dev` is required when working with Postgresql. `sudo apt install libpq-dev` should fix that error

2024-02-28 10:22 UTC, irevoire approved these changes
Ah yes perfect I see you updated the README as well thanks a lot!

bors merge

2024-02-28 10:27 UTC, merged