Update dependencies
meilisearch/meilisearch-rust pull request #542
Opened 2024-01-26 13:23 UTC by omid

Update dependencies and a bit of housekeeping.

2024-01-26 15:34 UTC, omid commented
There is a typo in `Cancelation`, but it's also like this in the app itself, so it's bigger than the sdk and most probably a breaking change!

2024-01-31 09:13 UTC, curquiza commented
Hello @omid 
thanks for the PR

We are ok with breaking changes since the app is not stable (using version format like v0.X.Y and not vX.Y.Z), so we can accept a PR. The most important is to be clear in the communication

2024-01-31 09:14 UTC, curquiza commented
Also @omid you said you updated the dependencies, but which ones?

2024-01-31 10:12 UTC, omid commented
@curquiza Thanks 🙏🏼 

> Also @omid you said you updated the dependencies but you also changed a lot of things

I updated `syn` to 2, `jsonwebtoken` to 9, and removed env_logger, since it wasn't in use.

> I don't feel comfortable accepting a PR where I have that much files to review for different reasons

If you don't mind, the update dep thingy changes are in just one commit which you can find [here](https://github.com/meilisearch/meilisearch-rust/pull/542/commits/61dc8ffc4cf590cb279f87e5eff0dd93aebe81a2).

> We are ok with breaking changes since the app is not stable (using version format like v0.X.Y and not vX.Y.Z), so we can accept a PR. The most important is to be clear in the communication

Sure, the only issue will be that the change should be applied everywhere! Including all SDKs I think, which I'm not familiar with their languages and it's a big chunk of work also.

2024-01-31 10:18 UTC, curquiza commented
> If you don't mind, the update dep thingy changes are in just one commit which you can find [here](https://github.com/meilisearch/meilisearch-rust/pull/542/commits/61dc8ffc4cf590cb279f87e5eff0dd93aebe81a2).

Not 100% true, this commit also change some parts of the code at the middle of the non-code related update:
https://github.com/meilisearch/meilisearch-rust/pull/542/commits/351651951e50155d4125a6df4ec23b914cfd1e0a

2024-01-31 10:18 UTC, curquiza commented
>Sure, the only issue will be that the change should be applied everywhere! Including all SDKs I think, which I'm not familiar with their languages and it's a big chunk of work also. (github said [50 files](https://github.com/search?q=org%3Ameilisearch%20cancelation&type=code) in the meilisearch org)

Can you point which kind of change you refer and why the issue is in all the SDKs?

2024-01-31 11:28 UTC, omid commented
> Can you point which kind of change you refer and why the issue is in all the SDKs?

As I said in the first post here, `There is a typo in *Cancelation*`. It's wrong, it's cancellation, double LL.

2024-01-31 11:31 UTC, omid commented
> Not 100% true, this commit also change some parts of the code at the middle of the non-code related update:

The update deps are in one commit. Others are typos and some housekeeping. There are some changes in the macro part in other commits, but they are not about the logic. Just code style, typo and so on.

2024-02-05 13:42 UTC, curquiza commented
Can you fix git conflicts?

2024-02-27 18:00 UTC, irevoire requested changes

2024-02-27 18:21 UTC, omid commented on meilisearch-index-setting-macro/src/lib.rs
> +                .wait_for_completion(&client, None, None)
You are absolutely right, my bad.

2024-02-28 10:16 UTC, irevoire approved these changes
Hey @omid thanks for your contribution it’s very nice, and updating syn was not an easy task!

We’re very grateful you did it; however, if you do it again, please follow curqui advice.
Do one PR that **only** updates the dependencies and another that only fixes typos.
That will make it way easier for us to review and merge (that’s also why I took so long to get back to you)

bors merge

2024-02-28 10:16 UTC, irevoire commented on meilisearch-index-setting-macro/src/lib.rs
> +}
That’s pretty nice, didn’t know about it before

2024-02-28 10:20 UTC, merged