fix(indexes): allow None `primary_key` in `add_or_update` function
meilisearch/meilisearch-rust pull request #557
Opened 2024-03-19 10:43 UTC by khanhnt2

# Pull Request

## Related issue
Cannot pass `None` value to `add_or_update` function

## What does this PR do?
Replace `impl AsRef<str>` to `&str`

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2024-03-20 11:09 UTC, curquiza requested changes
Hello @khanhnt2 
thank for this PR

can you add a test passing `None` value as primary key for the `add_or_update` function?

2024-04-07 09:37 UTC, khanhnt2 commented
Hi @curquiza , sorry for the late response. I added the test case.

2024-04-08 21:26 UTC, irevoire commented on src/indexes.rs
> +        primary_key: Option<&str>,
Hey, I’m not sure to understand what you changed here?

We could already send an option with the old API right?
> primary_key: Option<impl AsRef<str>>,

2024-04-15 14:20 UTC, curquiza commented
bors try

2024-04-15 14:48 UTC, irevoire approved these changes
bors merge

2024-04-15 16:02 UTC, irevoire approved these changes
bors merge

2024-04-15 17:07 UTC, curquiza approved these changes
bors merge

pliiiiiiz

2024-04-15 17:13 UTC, closed without merging