Add an example (wasm web app)
meilisearch/meilisearch-rust pull request #71
Opened 2020-11-21 15:32 UTC by Mubelotix

2020-11-22 10:44 UTC, Mubelotix commented
@curquiza I used the same HTML and CSS as [crates.meilisearch.com](crates.meilisearch.com). But I am unable to use one hosted CSS file because it contains relative URL paths for fonts so it doesn't work. I had to copy the content of this file and make a few modifications. So the `pkg/index.html` file of this PR contains a lot of things and it's not ideal.

2020-11-25 18:07 UTC, curquiza requested changes
Your tutorial is really great!! I requested small changes but the steps are really clear: I followed them without any troubles! Thanks 🙏

2020-11-25 18:07 UTC, curquiza commented on examples/web_app/README.md
> +This example is a clone of [crates.meilisearch.com](https://crates.meilisearch.com), but I rewrote the frontend in Rust.\
```suggestion
This example is a clone of [crates.meilisearch.com](https://crates.meilisearch.com), but the front-end is written in Rust! The Rust source files are compiled into WebAssembly and so can be readable by the browsers.

```

2020-11-25 18:07 UTC, curquiza commented on examples/web_app/README.md
> +It's using the same MeiliSearch server.
```suggestion
This tutorial is using the same MeiliSearch server as the original project, which means you can follow the next steps without running your own MeiliSearch instance.
```

2020-11-30 10:29 UTC, curquiza approved these changes
bors merge

2020-11-30 10:30 UTC, curquiza commented
Awesome work @Mubelotix! Thank you again!

2020-11-30 10:34 UTC, merged